version: '3'
services:
  redis:
    image: redis:alpine
  worker:
    build: .
    command: python worker.py
    depends_on:
      - redis
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - redis
